### ISSUE TITLE
local_data.json should NOT be checked into this repo

### ISSUE THREAD

**Issue by odscjames** [open-contracting/extension-explorer#10]
IMHO? Agree/disagree?

Doing so creates a lot of meaningless commits as we update it to the latest data, and also we end up with a lot of data here that will make the git repo much larger than it needs to be.

(I understand this was probably done for project kick off, which is fine - I just wanted to note it so we pick this up later.)

Instead we should set something up to automatically (or at least with a few well documented commands) include the other repository and build the data.

What we set up probably depends on how we want to deploy this website, so leaving for discussion with @kindly

**Comment by jpmckinney** [comment]
I agree that we shouldn't check in that file, which is the case in the present repo.

With respect to the larger issue of deployment and updates (whether automatic or manual), we can create follow-up issues (we won't forget as it is necessary).
