### ISSUE TITLE
Design Comments

### ISSUE THREAD

**Issue by kindly** [open-contracting/extension-explorer#16]
This issue is intended to collate comments about the design and minor layout changes to the extension-explorer website.
This supersedes issue #1.

Any issue about functionality or about what kind of things we display should be raised in individual separate issues.

**Comment by jpmckinney** [comment]
Looking at http://dev4.default.opendataservices.uk0.bigv.io:9090/en/, in no particular order:

# Version numbers

* Order on list pages: I think the numbered releases should be in reverse chronological order.
* Order in dropdown on extension page: This is in disorder.
* Appearance on list pages:
  * De-emphasize old versions within a minor series (e.g. by making the link lighter or grey), to encourage clicking on the latest version within a minor series
  * De-emphasize the list of versions as a whole, to encourage clicking on the extension name (e.g. by making it lighter or right-aligned)

# Extension page

## Header

* Use the full width for the extension name and for its description
* Version dropdown should have a 'Version' label

## Table of contents

* 'Docs' -> 'Documentation'
* 'Schema Reference' -> 'Schema' (to match 'Codelists', which isn't 'Codelists Reference')
* Increase the indentation (margin-left) of sub-lists as it presently computes to 4px, which is barely noticeable
* Special case the generation of the table of contents to ignore sub-headings of 'Changelog', to avoid, in future, having a long table of contents containing infrequently used links

## Documentation

* Don't repeat the extension name in the documentation
* Change the font size of the links that replace the Sphinx directives (should be paragraph text size)
* Change the text of the links that replace the Sphinx directives, as presently the target for the links is unpredictable (should be a sentence like 'View a table describing the Bid object' or 'View the codes within the bidStatus.csv codelist')

## Extension Info

* Eliminate this from the table of contents, as some of this information is key and should be more readily available:
  * Put a 'Download' button in the header (possibly right-aligned)
  * Include a simple instruction for declaring the extension in the header (using the 'Base URL' value)
  * Put 'Compatibility' in the header (possibly right-aligned)
  * Put a 'Core' badge (though word choice may change with #19) (possibly right-aligned)
  * Don't display the category anywhere

## Schema Reference and Codelists

* Increase the bottom padding/margin of tables to better separate the sections

**Comment by jpmckinney** [comment]
To resolve the issues relating to versions in lists of extensions, I simply removed the list of versions, as there is presently no reason to refer to old patch releases. When we have new minor versions of extensions, we might want to give access to the latest patch version of each minor version from lists of extensions. On the other hand, perhaps we should just leave version switching to the individual extension pages.
