### ISSUE TITLE
Rename ‘Core Extensions’ to ‘Recommended Extensions’

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/extension-explorer#19]
I would like to propose that the extension explorer rename ‘Core’ extensions to ‘Recommended’ extensions, and that it include a version of the following text at the top of the page.

> The main Open Contracting Data Standard covers data that is both widely available, and useful to a wide range of different users. 
> 
> Our recommended extensions describe how to publish: 
> 
> * Additional data that exists in some countries, but not others due to the way contracting processes work, but that should always be published when it exists (e.g. Lots); 
> 
> * Additional data that describes important features of a contracting process, but which may not be possible to publish in all countries, or for all kinds of contracting process (e.g. Bid details);
> 
> * Additional data that has widespread value to users, but that often requires publishers to make specific plans to collect this data, or to collect it in a structured way (e.g. Lots).
>
> These extensions are maintained alongside the core standard, and go through the same governance process as OCDS, in order to make sure they represent the needs of a wide community. 
>
> We encourage all users of OCDS to consider whether these extensions could be used with their data, and where they lack the data needed to use an extension, to consider whether this could be collected in future. “

At the bottom of the page we could include:

>Note: Recommended extensions were previously called ‘Core Extensions’. The name was updated in 2018 to better reflect their purpose. “

The description above would work for all current core extensions with the exception of “Milestone documents” for which either:

(a) We move it to be a community extension (not strictly allowed without a 1.2 I think, but we might be able to justify doing that in a bug-fix release)

(b) We add some special handling for this case, and add a section to the bottom of the ‘Recommended extensions’ page where ‘Milestone documents’ would display, with the following heading and description:

> 
> **Extensions covering deprecated fields**
> 
> When certain features of OCDS are deprecated, we may in some cases maintain extensions that ‘add back’ those features. These are provided so that users declaring use of these extensions do not receive data validation errors when using the deprecated properties. These use of these extensions **is not** recommended unless you have previously been using the fields and data structures they specify.

**Comment by jpmckinney** [comment]
I'm not sure on the best name for 'core extensions' (acknowledging that 'core extensions' is confusing). For instance, if we have 'recommended' and 'community', there's a potential implication that community extensions aren't recommended.

The most important distinction is that 'core extensions' are reviewed through the governance process, whereas 'community extensions' are not. The current names suggest who the likely/desired authors are, though so far we've led the development of most community extensions. If we wanted to name the extension-types to focus on the governance distinction, it'd be along the lines of 'standard' / 'non-standard', 'governed' / 'ungoverned', 'reviewed' / 'unreviewed', 'normative' / 'non-normative' (though these aren't great suggestions). (In W3C, 'recommended' has the connotation of 'standardized', but outside that context, it's not generally understood that way.)

We can perhaps consider 'Standards Track Extensions' and 'Other Extensions'.

The name 'local extension' refers to the context of application of the extension (rather than its governance or authorship), but that seems fine to me.

**Comment by timgdavies** [comment]
+1 to language of 'Registered extensions'. I think this captures that well.

On 'Recommended' - I think there is an extent to which core extensions are **more recommended** than community. They don't just become core because they are more maintained than others - but also because there is strong enough evidence that they meet multiple user needs, and that it is important that this data is published. 

In this sense it is 'recommended' vs 'optional' rather than the opposite being '**not** recommended'. 

I think 'standards track' places too much emphasis on the technical aspect of these, and not enough on the policy dimension of why these are put as core. 

In essence I think we are trying to get to something like: 

* Strong SHOULD - the core standard - you should have a good reason for not providing the fields of data it asks for.
* Weak SHOULD - what are currently core extensions - this is good to publish, but we're more understanding right now of cases when it isn't.
* MAY - what are currently community extensions - if these are useful, use them - but otherwise - no pressure. 

Whilst the terminology might be slightly tricky - I think we can tighten up meaning in prose that accompanies the terms. Getting away from 'core' though I think would be progress.

**Comment by jpmckinney** [comment]
Agreed – we can consider 'recommended'. Some synonyms we might consider using instead:

* promoted
* endorsed
* suggested
* supported
* encouraged

If we want to lean more heavily on the angle of "you're doing a good thing by using these extensions" to promote their use (similar to the language of 'basic-intermediate-advanced', where publishers have a desire to be 'advanced'), we might consider other language like 'OCDS Plus' (not the best, just trying to spur the imagination), such that publishers may have a motivation to be an 'OCDS Plus' (or whatever other name) publisher – similar to how publishes have a motivation to be the first to publish certain kinds of data (e.g. implementation data).

Does either any synonym or alternate name (both open to additional suggestions) work better than 'recommended'?

**Comment by duncandewhurst** [comment]
'Supported' could be good to distinguish the level of helpdesk support publishers should expect with using different types of extension (though we didn't really define that yet) in addition to fitting with how the extensions are maintained, though I think 'recommended' fits better with implying that using the extensions is a good thing.

**Comment by jpmckinney** [comment]
This has been implemented as a filter on the extensions page, without the verbiage (which we can choose to put somewhere).
