### ISSUE TITLE
Rename Community Extensions -> Library (and include 'core' extensions there too)

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/extension-explorer#20]
In tandem with #19 I would like to suggest we rename ‘Community extensions’ to ‘Extension Library’ and:

* [x] Include all extensions in here, but visually mark ‘recommended’ (i.e. core) extensions in some way.

* [x] Visually mark on the cards the GitHub repo an extension is from  (i.e. to show when they are open-contracting maintained or not)

* [ ] Include the pre-amble below at the top of the page:

> The extensions library contains extensions developed by the OCDS team, and by members of the OCDS community. 
>
> Many extensions have been developed to meet a particular publisher or user need. They are included in the extension library if they are likely to be relevant to more than one publisher, user or use-case. 

The reason for this suggestion is that, whilst we want to draw particular attention to recommended extensions *somewhere*, we don't want people who are browsing extensions to miss finding a core extension that could have been useful to them. 

Using visual cues, rather than silos, to indicate the extent to which an extension is 'recommended' / 'strongly encouraged', or the extent to which it can be trusted as reliable, may help us in future.

**Comment by jpmckinney** [comment]
I think it makes sense to have a page with all extensions.

In terms of authorship, there's an [open issue](https://github.com/open-contracting/extension_registry/issues/97) to add these details to `extension.json`, which the Extension Explorer can then display for each extension.

With respect to #19, I think we still need a public name to refer to non-core extensions. If we rename core extensions to 'recommended extensions', but don't have a name for other extensions, I think the default might be that users end up thinking of / referring to them as 'non-recommended extensions', which isn't the semantics I think we want. Anyhow, we can continue that in #19 :)

**Comment by jpmckinney** [comment]
As extensions aren't guaranteed to be hosted on GitHub, and as the Extension Explorer shouldn't really have logic for parsing download URLs to determine authorship, we'll punt the second item until  https://github.com/open-contracting/extension_registry/issues/97 is resolved.
