### ISSUE TITLE
Handling versions: user stories and suggestions

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/extension-explorer#21]
I'll start with three user stories:

* AS A data publisher following a link from OCDS 1.1, I WANT TO be linked to the version of an extension that is relevant to me without needing to think about it SO THAT I use the correct extension version.”

* AS A policy maker concerned with our ‘compliance’ with open contracting I WANT TO know exactly which core extensions we should be using SO THAT I’m not at risk of trying to hit a moving target”

* “AS A developer implementing a commitment to publish to OCDS 1.1 I WANT TO have an extension selector that lets me get the code I need for all the 1.1 versions of OCDS core extensions SO THAT I don’t risk using the wrong version of each extension” 

At the moment the display of versions feels quite confusing (reflecting some underlying confusion in our versioning approach I think).

**In theory:**

* For **core** extensions, the standard pins a particular version. If I link from OCDS 1.1.3 -> extension explorer, I should be shown the list of core extensions as pinned in OCDS 1.1.3;

* For **community** extensions I should generally be taken to the the latest version compatible with the version of OCDS I am working with, and only then offered chance to check other versions;

**Suggestions**

* We make sure the OCDS documentation at http://standard.open-contracting.org/latest/en/extensions/ lists the recommended extensions, and the particular versions of these ‘pinned’ by that version of OCDS, linking to that specific version of the docs;

* We make sure it possible to link to the extension selector, with it pre-filtered to display only **core** extensions, and using the versions pinned for a specific OCDS version (e.g. 1.1.3) [NOTE: It is not inevitable that OCDS version 1.1.3 will always pin an extension version 1.1.3; When we OCDS 1.2, it could continue to pin to extension versions 1.1.3 if those versions have not changed. This maintains the semantic versioning property of the extension version number). 

* We add a bit of documentation (possibly just tooltip style) to version information to explain “OCDS extensions are expected to follow semantic versioning principles, using the major (1.x.x) number to indicate backwards compatibility, and the minor and patch number to indicate new features and bug fixes respectively.” 

**Additional suggestions**

* We add a drop-down to the top of the screen to select which version of OCDS you are currently dealing with (and allow this to be set via parameter / cookie etc.)

* We use something dynamic to then highlight which versions of the extension are compatible with that version of OCDS (using the compatibility fields from extension.json)

* We rename ‘master’ to ‘latest’  - as ‘latest’ is a more familiar label to users (ReadTheDocs does this for example… - well, sort of, it takes the default branch from GitHub as latest, even if that’s not called master - we might want to do the same) 

Mock up here:

![image](https://user-images.githubusercontent.com/342624/45223007-f556e880-b2ad-11e8-9059-ae2654c81d53.png)

(Note: as I go through this, I wonder if with the suggestion in  #20 that we include **all** extensions in the ‘library’, and visually mark ‘recommended’ extensions, whether we even need separate ‘core’ and ‘community’ sections. We can handle listing which extensions are ‘core’/‘recommended’ for a particular version of OCDS within the OCDS documentation itself, just linking out to the explorer as required).

**Comment by jpmckinney** [comment]
There's a bit of complexity around the handling of patch versions.

Conceptually, each version of OCDS should refer to a *minor* version of an extension. For example, OCDS 1.1.3 would refer to version 4.5 of ocds_ipsum_extension (a fictional core extension). If a new patch version of ocds_ipsum_extension is released after 1.1.3, users should be led to use that patch version (e.g. 4.5.2), not the patch version that was available when 1.1.3 was released (e.g. 4.5.1). This allows bugfixing core extensions without releasing a new version of OCDS.

I'll comment on the display of version numbers elsewhere, but in short, old patch releases should be de-emphasized (whether gray text, small text, harder-to-reach text, etc.).

**Comment by jpmckinney** [comment]
With respect to having a page for core extensions only, let's keep that discussion separate, in #20. On the tech check-in call today, we discussed a possible feature of listing groups / collections / packs of extensions, which might include: profile extensions (e.g. PPP), thematic extensions (e.g. budgetary), etc. – and, if we were to remove 'core extensions' from the main navigation, we could have such a page to list core extensions.

**Comment by jpmckinney** [comment]
> We make sure the OCDS documentation at http://standard.open-contracting.org/latest/en/extensions/ lists the recommended extensions, and the particular versions of these ‘pinned’ by that version of OCDS, linking to that specific version of the docs;

Yes, noted in #3.

> We make sure it possible to link to the extension selector, with it pre-filtered to display only core extensions, and using the versions pinned for a specific OCDS version (e.g. 1.1.3) [NOTE: It is not inevitable that OCDS version 1.1.3 will always pin an extension version 1.1.3; When we OCDS 1.2, it could continue to pin to extension versions 1.1.3 if those versions have not changed. This maintains the semantic versioning property of the extension version number).

The extension selector was not developed in the sprint, but if we collect sufficient demand and requirements, we can consider this feature if/when it is developed.

> We add a bit of documentation (possibly just tooltip style) to version information to explain “OCDS extensions are expected to follow semantic versioning principles, using the major (1.x.x) number to indicate backwards compatibility, and the minor and patch number to indicate new features and bug fixes respectively.”

A bit long for a tooltip, but we can integrate it into a new page answering general questions about extensions.

> We add a drop-down to the top of the screen to select which version of OCDS you are currently dealing with (and allow this to be set via parameter / cookie etc.)

> We use something dynamic to then highlight which versions of the extension are compatible with that version of OCDS (using the compatibility fields from extension.json)

Until OCDS 1.2, this drop-down will only contain 1.1, and there is only one version of OCDS with which to be compatible, so leaving these for later.

> We rename ‘master’ to ‘latest’ - as ‘latest’ is a more familiar label to users (ReadTheDocs does this for example… - well, sort of, it takes the default branch from GitHub as latest, even if that’s not called master - we might want to do the same)

I think we'd want the website versions to match the versions in extension URLs and on GitHub. GitHub creates permanent redirects for repository renaming, but not for branch renaming. We'd therefore have to add a `latest` branch that we manually mirror to the `master` branch.  I think that's too much trouble. Instead, I've just added "(latest)" after "master" in the version dropdown.
