### ISSUE TITLE
Custom listings of groups of extensions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/extension-explorer#24]
On the tech check-in call today, we discussed a possible feature of listing groups / collections / packs of extensions, which might include: profile extensions (e.g. PPP), thematic extensions (e.g. budgetary), etc. – and, if we were to remove 'core extensions' from the main navigation per #21, we could have such a page to list core extensions.

I assume these pages would be configured within this repository. One option is to have a YAML file for each listing (or one YAML file for all listings), with the URL slug and title of the page, and a list of extension names (I only describe this option to give a sense of how I think it could work). Profiles might need a special case.

**Comment by odscjames** [comment]
> I assume these pages would be configured within this repository.

Actually, I'd say there shouldn't be data here. Currently neither data-collector or this repo hold their own data - they both get data from elsewhere. 

I'd suggest this should be configured in the https://github.com/open-contracting/extension_registry and we let the data-collector check and report on this info, and it appears on the website from there. 

This will help others who want to reuse the extension data for other needs and will also keep a clean concept of which repositories hold code only and which hold data (the registry).

**Comment by jpmckinney** [comment]
From a product perspective, the registry's responsibilities are to:

* list registered extensions and versions ('registered' means passing a bar for quality, relevance, etc.)
* describe the 'core' status of extensions ('core' means following the governance process)

In other words, the registry has a normative role. Due to how extensions are presently included in the OCDS documentation, the registry also stores a category for each extension, but this is presentation layer information and isn't essential to the role of the registry.

From a product perspective, the explorer's responsibilities are (among others) to:

* present information about each extension and its versions
* assist users in finding and browsing extensions

In other words, the explorer has an informative role. Assigning extensions to categories and presenting those categories fits with the responsibilities of the explorer.

I don't think we need to be pure about the separation of code and data. The product owner of the registry shouldn't have to know whether an extension appears on a list of finance extensions or implementation extensions, etc. When a new extension is authored, the product owner shouldn't be expected to think about what pages of the explorer an extension should appear on. The product owner of the extension explorer, on the other hand, does concern themselves with such questions. So, I don't think it makes sense for the registry to store this information. Something else should store it.

**Comment by jpmckinney** [comment]
Another group should be Profiles (PPPs, EU, GPA, etc.).

**Comment by jpmckinney** [comment]
This has been implemented as a set of filters on the page with the list of extensions.
