### ISSUE TITLE
Permanent hosting for this

### ISSUE THREAD

**Issue by odscjames** [open-contracting/extension-explorer#32]
We set up temporary hosting for this, to enable good user feedback sessions to go ahead. But it is definitely temporary hosting, and while there are many other tasks still to get right before a public launch we should discuss the plan for permanent hosting.

I've been looking into this and trying some code ....

So the suggestion is to use Travis to build the static site and then to push that static site to a simple web server, in a manner similar to what we do for the standard.

The Travis build will run in a separate repository ( https://github.com/open-contracting/extension-explorer-build ??? ), and will run once a day on a cron job.

You can see an experimental set of scripts at https://github.com/odscjames/test-extensions-explorer-site These do everything except upload to a web server (that would be set up for master branch only).

You can see a build for these at https://travis-ci.org/odscjames/test-extensions-explorer-site/builds/428595924 - it lists all the files it has built.

**Why Travis?**

Easy to set up, all the user access for actions like "rebuild" are already done, state and errors of process are public for all to see.

**Why not the https://github.com/open-contracting/extension-explorer repo?** 

Because we wanted to keep builds for this repository deterministic, so that if a developer is working on a new branch and starts to get errors they know the error is something they have done and not another change outside the repository that is hard or impossible to track down. 

It would be very difficult or maybe impossible to cleanly add deploy stuff to this repo without that coming in (as the deploy stuff would need the data from extensions-data-collector and then you lose the deterministic aspect).

So it may be possible, but it would start to make the Travis process quite complicated. The only benefit of putting the deploy in here is that you would automatically get the website redeploying everytime you merged to master instead of up to 24 hours later, but as we don't anticipate that many urgent changes we don't think that's important - and if there are any important changes it's possible to go to Travis and push "rebuild" on the last build to get a deploy anyway.

**Which server?**

Just an Apache Linux Open Data Services one, similar to https://raw.githubusercontent.com/OpenDataServices/opendataservices-deploy/master/open-contracting-standard-deploy.sh - I haven't looked into the details of this yet but don't anticipate any issues here.

_Posting for comments and feedback ....._

**Comment by jpmckinney** [comment]
Is GitHub Pages an option?

**Comment by odscjames** [comment]
As in, the Travis script builds the output files then commits them back to a _gh-pages_ branch for GitHub to serve?

I'd rather not because then you end up with a long GitHub branch that tracks a lot of changes and starts to take up a lot of space that is difficult to reclaim, and there is no need or benefit to that.

If you want to think about alternate places to serve the pages from, my first suggestion would be to push the files to an AWS S3 bucket and then use AWS Cloudfront CDN to serve from there with a SSL cert. (If you don't like AWS I think other providers offer similar services, maybe https://www.digitalocean.com/products/spaces/ would do for instance)

**Comment by jpmckinney** [comment]
AWS S3 with Cloudfront also sounds fine.

The benefit to GitHub Pages is that there is no additional account or service to care for.

For GitHub Pages, it can be in a different repository (on any branch – I think GitHub now lets you select which one to serve via GitHub Pages). If we re-build daily, it will have 365 commits per year, which is not that high. I don't expect it will take a lot of space, as git stores text (and text changes) efficiently. The fact that the change history is unimportant isn't a strong reason to avoid this option.

**Comment by jpmckinney** [comment]
I used the official Travis docs for [GitHub Pages deployment](https://docs.travis-ci.com/user/deployment/pages/), which force pushes to avoid tracking history unnecessarily. I did it in this repo on the `gh-pages` branch. It just required a few lines in `.travis.yml`. Builds are still deterministic, as the deploy only occurs after the build.

http://extensions.open-contracting.org
