### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/extension-explorer#4]
I had a quick look at https://github.com/open-contracting/extension-explorer/blob/gh-pages/extension_explorer/__init__.py

[It's possible for a community extension to be promoted to a core extension](https://docs.google.com/document/d/1zvR1PDefO6yTK28uKA6XCnxMLiC9oiEeb3uFjHuRyqI/edit#heading=h.yulq3jvl2ro). So, to have more or less permanent URLs, `core` and `community` should not be part of the path to an extension.

Based on the [context shared about core extension versioning](https://github.com/open-contracting/extension-explorer/issues/1#issuecomment-404587713), a core extension's version should come after the extension's ID in the URL, since core extensions are not guaranteed to be released as a series.

So, I figure the sitemap would look like, for the routes configured thus far:

```
/
/<lang>/
/<lang>/extensions/<extension>/<version>/
```

I used an `/extensions/` path component, to avoid conflict between extension names and whatever other pages we add to the sitemap.

**Comment by robredpath** [comment]
We're happy to use this pattern ^^ . Once we've built the website there may of course be feedback that means that we want to revisit this decision but we're happy with it at this stage and can't foresee any issues. 

@jpmckinney is any further discussion needed to hear from other people who might care about this?

**Comment by jpmckinney** [comment]
Sounds good, and I don't think so. These paths are very similar to the standard's, e.g. http://standard.open-contracting.org/1.1/en/extensions/bids/
