### ISSUE TITLE
Extension compatibility considerations

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/extension-explorer#5]
It's presently the extension author's responsibility to declare their extension's compatibility with minor versions of OCDS in extension.json. 

However, we might anticipate that not all authors will update their extension.json when a new major/minor version of OCDS is released (even if the new version requires no other changes to their extension).

However, we would still like to be able to list extensions that are known to be compatible with a version of OCDS, even if the extension itself doesn't declare it as compatible.

There are a variety of potential solutions, but just describing the desire for now.

**Comment by odscjames** [comment]
I don't see a major problem adding something to help with this.

For now, i have made https://github.com/open-contracting/extensions-data-collector/issues/18

When this is done, the website should display compatibility info from these new fields. 

Then this user requirement can be dealt with in the https://github.com/open-contracting/extensions-data-collector at a future point.

**Comment by jpmckinney** [comment]
Closing for now, as no tool to my knowledge checks compatibility of extensions. If my assumption in the issue description ends up being correct, we can explore overriding the compatibility when generating the extensions data file.
