### ISSUE TITLE
Hide deprecated fields on schema page

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/extension-explorer#63]
I got very confused looking at the pagination extension because the [schema page](https://extensions.open-contracting.org/en/extensions/pagination/master/schema/) shows lots of deprecated fields.

I think we should hide or collapse them, or at least indicate which fields are deprecated.

**Comment by jpmckinney** [comment]
It's the only extension with deprecated fields, and I don't know why I did that. I've removed the fields now. They'll disappear once the site is regenerated.
