### ISSUE TITLE
Show release and record package fields on schema page

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/extension-explorer#64]
The pagination extension patches `release-schema.json`, `release-package-schema.json` and `record-package-schema.json` but only the fields in `release-schema.json` are shown on the [schema page](https://extensions.open-contracting.org/en/extensions/pagination/master/schema/).

We should display fields from all schemas patched by an extension.

**Comment by jpmckinney** [comment]
This only affects the pagination extension. With 1.2, packaging is set to change, and there's a good chance pagination (or at least links like in JSON Hyper-Schema) will be made part of OCDS #928.

As such, extending packages will be a thing of the past. I'm okay with one extension being badly displayed until 1.2, after which it won't matter. In the meantime, the pagination readme is clear enough.
